export const projects = [
  {
    id: 1,
    title: "Auravia",
    category: "E-COMMERCE",
    year: "2025",
    description: "Premium luxury jewelry e-commerce platform featuring elegant gold, diamond, and gemstone collections with sophisticated shopping experience.",
    thumbnail: "/projects/auravia.jpg",
    link: "https://auravia.co.in",
    client: "Auravia Jewellers",
    isRecent: true,
  },
  {
    id: 2,
    title: "Future Oil Conference",
    category: "EVENT WEBSITE",
    year: "2025",
    description: "Annual oil and gas industry conference platform bringing together industry leaders and experts to discuss latest trends.",
    thumbnail: "/projects/future-oil.jpg",
    link: "https://futureoilconference.com/",
    client: "Aro Events",
  },
  {
    id: 3,
    title: "Divya Chemical Industries",
    category: "CORPORATE",
    year: "2025",
    description: "Industrial chemical company website showcasing products and services with professional corporate design.",
    thumbnail: "/projects/divya-chemical.jpg",
    link: "https://www.divyachemicalindustry.com",
    client: "Divya Chemical Industries",
  },
  {
    id: 4,
    title: "Aro Events",
    category: "EVENT MANAGEMENT",
    year: "2025",
    description: "Event management company specializing in organizing conferences, seminars, and corporate workshops.",
    thumbnail: "/projects/aro-events.jpg",
    link: "https://www.aroevents.com/",
    client: "Aro Events",
  },
  {
    id: 5,
    title: "Smile Cafe Point",
    category: "FOOD ORDERING",
    year: "2024",
    description: "Web application for viewing menu items, ordering food, and managing cart for a cafe business.",
    thumbnail: "/projects/smile-cafe.jpg",
    link: "https://cafeteria-hkg1dqqcq-monuhundlani-gmailcoms-projects.vercel.app",
    client: "V-ex Tech Solutions",
  },
  {
    id: 6,
    title: "Find House",
    category: "REAL ESTATE",
    year: "2024",
    description: "Real estate platform for searching houses, viewing property details, and saving favorites.",
    thumbnail: "/projects/find-house.jpg",
    client: "Dubai Client",
  },
  {
    id: 7,
    title: "VHX View",
    category: "E-COMMERCE",
    year: "2024",
    description: "Online clothing store offering trendy, high-quality apparel designed to elevate everyday style.",
    thumbnail: "/projects/vhx-view.jpg",
    client: "Owner Of VHX View",
  },
  {
    id: 8,
    title: "AI Wave",
    category: "AI APPLICATION",
    year: "2024",
    description: "AI-powered image generation platform where users can enter prompts to create unique artwork.",
    thumbnail: "/projects/ai-wave.jpg",
    client: "Personal Project",
  },
  {
    id: 9,
    title: "Clothophile",
    category: "FASHION",
    year: "2024",
    description: "Fashion e-commerce platform for browsing latest trends, shopping clothing, and managing cart.",
    thumbnail: "/projects/clothophile.jpg",
    client: "Personal Project",
  },
  {
    id: 10,
    title: "Smart Cab Point",
    category: "BOOKING PLATFORM",
    year: "2023",
    description: "Taxi booking application with booking forms, cab selection, and trip management features.",
    thumbnail: "/projects/smart-cab.jpg",
    link: "https://smart-cab-monuhundlani-gmailcoms-projects.vercel.app",
    client: "V-ex Tech Solutions",
  },
  {
    id: 11,
    title: "Soccer Master",
    category: "SPORTS",
    year: "2023",
    description: "Football news platform featuring latest news, match fixtures, results, and sports updates.",
    thumbnail: "/projects/soccer-master.jpg",
    link: "https://soccer-master-1n289oapc-monuhundlani-gmailcoms-projects.vercel.app",
    client: "Spider Academy",
  },
  {
    id: 12,
    title: "Trydo Agency",
    category: "CREATIVE AGENCY",
    year: "2024",
    description: "Digital agency website specializing in creating stunning websites and applications for businesses.",
    thumbnail: "/projects/trydo.jpg",
    client: "Personal Project",
  },
  {
    id: 13,
    title: "Artful Corner",
    category: "INTERIOR DESIGN",
    year: "2022",
    description: "Interior design studio portfolio showcasing projects and design services.",
    thumbnail: "/projects/artful-corner.jpg",
    link: "https://artful-corner-interiar-design-studio.netlify.app",
    client: "Artful Corner Studio",
  },
  {
    id: 14,
    title: "Portfolio v1",
    category: "PORTFOLIO",
    year: "2023",
    description: "Personal portfolio website showcasing web development skills and project work.",
    thumbnail: "/projects/portfolio.jpg",
    link: "https://portfolio-xi-ruddy-52.vercel.app/",
    client: "Personal Project",
  },
]

export type Project = typeof projects[number]
